# Generated by Django 4.2.6 on 2024-09-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_copytradeaccessrequest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('user_address', models.CharField(blank=True, max_length=300, null=True)),
                ('fraud_address', models.CharField(blank=True, max_length=300, null=True)),
                ('exchange_platform', models.CharField(blank=True, max_length=300, null=True)),
                ('fraud_proof', models.FileField(blank=True, null=True, upload_to='recover')),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='recover-payment')),
            ],
        ),
    ]
