# Generated by Django 4.2.6 on 2024-09-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_trackingpayment_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackingpayment',
            old_name='exchange_platform',
            new_name='fraud_platform',
        ),
        migrations.AddField(
            model_name='trackingpayment',
            name='user_platform',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
