# Generated by Django 4.2.6 on 2024-10-27 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_exchange_platform_trackingpayment_fraud_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=1000, null=True)),
                ('entry', models.CharField(blank=True, max_length=1000, null=True)),
                ('take_profit', models.CharField(blank=True, max_length=1000, null=True)),
                ('stop_loss', models.CharField(blank=True, max_length=1000, null=True)),
                ('portfolio', models.CharField(blank=True, max_length=1000, null=True)),
                ('profit_or_loss', models.CharField(blank=True, max_length=1000, null=True)),
                ('ROI', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('Entered', 'Entered'), ('Closed', 'Closed')], max_length=1000, null=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_trades', to='accounts.copytrader')),
            ],
        ),
    ]
