# Generated by Django 4.2.6 on 2024-10-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_experttrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='copytrader',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
