# Generated by Django 4.2.6 on 2024-11-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_experttrade_shares_amount_profile_expert_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expert_profit',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
