# Generated by Django 4.2.6 on 2025-04-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_profile_expert_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_document',
            field=models.ImageField(blank=True, null=True, upload_to='address-documents'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_verification',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('unverified', 'unverified'), ('verified', 'verified')], default='unverified', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_backpage_document',
            field=models.ImageField(blank=True, null=True, upload_to='identity-documents'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_frontpage_document',
            field=models.ImageField(blank=True, null=True, upload_to='identity-documents'),
        ),
        migrations.AddField(
            model_name='profile',
            name='identity_verification',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('unverified', 'unverified'), ('verified', 'verified')], default='unverified', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
