# Generated by Django 4.2.6 on 2025-04-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_address_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Declined', 'Declined')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Declined', 'Declined')], default='Pending', max_length=30),
        ),
    ]
